export const poemas = [
  "[nombre], En tus ojos encuentro el cielo, en tus abrazos, todo el anhelo. [nombre], Eres mi sol, mi razón de ser, en cada verso, te vuelvo a querer.",
  "[nombre], Tu risa es música que alegra mi ser, tus besos son fuego que me hace arder. [nombre], Eres mi refugio, mi paz y mi hogar, en tus brazos encuentro mi lugar.",
  "[nombre], Eres el sueño que nunca quiero despertar, el amor que siempre he deseado encontrar.[nombre], En cada mirada, siento el universo, contigo, mi amor, todo es más inmerso.",
  "[nombre], Tus palabras son versos que encienden mi piel, tu presencia es un regalo que siempre anhelé.[nombre], Eres la melodía que alegra mi corazón, en cada momento, eres mi única razón.",
  "[nombre], En tu sonrisa encuentro la felicidad, en tus caricias, la más dulce tranquilidad. [nombre], Eres mi inspiración, mi musa y mi amor, contigo, mi vida, es un eterno esplendor.",
  "[nombre], Tus manos son mi refugio en la tormenta, tu voz, un susurro que calma mi aflicción. [nombre], Eres el faro que guía mi camino, en cada paso, eres mi eterno destino.",
  "[nombre], Eres el sueño que siempre imaginé, la realidad que supera cualquier fantasía. [nombre], Eres mi confidente, mi cómplice y mi amigo, en cada momento, contigo quiero estar abrigo.",
  "[nombre], Cada latido de mi corazón lleva tu nombre, cada pensamiento está lleno de tu amor. [nombre], Eres mi razón de ser, mi todo y mi esencia, en cada instante, eres mi más bella presencia.",
  "[nombre], Tus besos son la lluvia que moja mi piel, tu abrazo, el refugio donde quiero ser fiel. [nombre], Eres mi fortaleza, mi apoyo y mi guía, en cada paso, contigo quiero caminar cada día.",
  "[nombre], Eres el sueño que se hizo realidad, el amor que siempre he anhelado encontrar. [nombre], En cada mirada, veo nuestro futuro, juntos, mi amor, superaremos cualquier muro.",
  "[nombre], Tus palabras son versos que acarician mi alma, tu sonrisa, un sol que ilumina mi calma. [nombre], Eres mi inspiración, mi luz y mi pasión, en cada momento, eres mi eterno corazón.",
  "[nombre], En tus abrazos encuentro la paz, en tus besos, el amor que siempre deseo más. [nombre], Eres mi confidente, mi cómplice y mi alegría, en cada instante, contigo quiero vivir cada día.",
  "[nombre], Eres el sueño que siempre quise soñar, el amor que nunca quiero dejar escapar. [nombre], En cada mirada, veo nuestro destino, juntos, mi amor, construiremos un camino.",
  "[nombre], Tus caricias son el viento que acaricia mi piel, tu voz, la melodía que siempre quiero oír. [nombre], Eres mi refugio, mi paz y mi consuelo, en cada paso, contigo quiero volar en vuelo.",
  "[nombre], En tus ojos encuentro el paraíso, en tus palabras, el amor que siempre preciso. [nombre], Eres mi compañero/a en esta danza llamada vida, juntos, mi amor, superaremos cualquier herida.",
  "[nombre], Eres el sueño que siempre quise alcanzar, el amor que nunca quiero dejar de amar. [nombre], En cada mirada, veo nuestro horizonte, juntos, mi amor, enfrentaremos cualquier monte.",
  "[nombre], Tus abrazos son el refugio que siempre busqué, tus besos, el fuego que siempre encendí. [nombre], Eres mi inspiración, mi razón de ser, en cada instante, contigo quiero florecer.",
  "[nombre], En tus caricias encuentro la calma, en tus palabras, la ternura que siempre me acalma. [nombre], Eres mi fortaleza, mi apoyo y mi amor, en cada paso, contigo quiero vivir con fervor.",
  "[nombre], Eres el sueño que siempre quise soñar, el amor que nunca quiero dejar de abrazar. [nombre], En cada mirada, veo nuestro destino, juntos, mi amor, construiremos un camino.",
  "[nombre], Tus ojos son el reflejo de mi felicidad, tu sonrisa, el sol que ilumina mi realidad. [nombre], Eres mi compañero/a en esta aventura, en cada momento, mi amor, eres mi eterna ternura.",
  "En el jardín de tu sonrisa, [nombre], florece mi amor, con cada rayo de sol que ilumina tu rostro, crece mi pasión por ti.",
  "Eres como una melodía, [nombre], que no deja de sonar en mi mente, cada nota, cada acorde, es un eco de mi amor por ti.",
  "[nombre], eres mi faro en la oscuridad, mi sol en un día nublado, mi calor en el frío invierno, y mi amor por siempre.",
  "Si el amor fuera un lienzo, [nombre], tú serías mi obra maestra, cada trazo, cada color, es un reflejo de mi amor por ti.",
  "Eres mi sueño hecho realidad, [nombre], cada día a tu lado es un regalo, y mi amor por ti no conoce límites.",
  "Como el viento que acaricia las hojas, así es mi amor por ti, [nombre], suave pero constante, siempre presente.",
  "Eres mi luna, [nombre], iluminando mis noches más oscuras, y mi amor por ti es como las estrellas, infinito y siempre brillante.",
  "En el libro de mi vida, [nombre], eres mi capítulo favorito, cada palabra, cada línea, es una muestra de mi amor por ti.",
  "Eres mi refugio, [nombre], en medio de la tormenta, mi paz en el caos, y mi amor por ti es mi ancla.",
  "Como el mar ama a la luna, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el océano.",
  "Eres mi sol, [nombre], iluminando mi mundo, y mi amor por ti es como el cielo, sin fin y siempre azul.",
  "Eres mi poesía, [nombre], cada palabra, cada verso, es un reflejo de mi amor por ti.",
  "Como un río que fluye hacia el mar, así fluye mi amor hacia ti, [nombre], constante e inmutable.",
  "Eres mi canción, [nombre], cada nota, cada melodía, es un eco de mi amor por ti.",
  "Eres mi sueño, [nombre], y mi amor por ti es la realidad que quiero vivir cada día.",
  "Como el sol ama a la tierra, así te amo yo, [nombre], mi amor por ti es tan brillante y eterno como el sol.",
  "Eres mi todo, [nombre], mi sol, mi luna, mis estrellas, y mi amor por ti es tan infinito como el universo.",
  "Eres mi arco iris, [nombre], apareciendo después de la lluvia, llenando mi vida de color, y mi amor por ti es mi promesa de siempre.",
  "Eres mi luz, [nombre], guiándome a través de la oscuridad, y mi amor por ti es mi faro.",
  "Eres mi sueño, [nombre], y cada día a tu lado es un sueño hecho realidad, mi amor por ti es la realidad que siempre quise.",
  "Eres mi amanecer, [nombre], cada día contigo es un nuevo comienzo, y mi amor por ti es el sol que ilumina mi camino.",
  "Como un árbol en plena primavera, así florece mi amor por ti, [nombre], con cada brote, cada hoja, crece mi pasión.",
  "[nombre], eres mi melodía favorita, la canción que no puedo dejar de cantar, y cada nota es un eco de mi amor por ti.",
  "Eres mi estrella, [nombre], brillando en la oscuridad, guiándome a través de la noche, y mi amor por ti es tan infinito como el cielo.",
  "Eres mi refugio, [nombre], mi lugar seguro en medio de la tormenta, y mi amor por ti es mi ancla, siempre firme.",
  "Como una brisa suave en un día de verano, así es mi amor por ti, [nombre], refrescante y constante.",
  "Eres mi sol, [nombre], iluminando mi mundo, y mi amor por ti es tan brillante y eterno como el sol.",
  "Eres mi poesía, [nombre], cada palabra, cada verso, es un eco de mi amor por ti.",
  "Como el río ama al mar, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el océano.",
  "Eres mi luna, [nombre], iluminando mis noches, y mi amor por ti es como las estrellas, siempre brillante.",
  "Eres mi canción favorita, [nombre], la melodía que siempre quiero escuchar, y cada nota es un reflejo de mi amor por ti.",
  "Como un faro en la oscuridad, así eres tú para mí, [nombre], mi guía, mi luz, y mi amor por ti es mi camino.",
  "Eres mi sueño hecho realidad, [nombre], y cada día contigo es un regalo, mi amor por ti es mi mayor tesoro.",
  "Eres mi todo, [nombre], mi sol, mi luna, mis estrellas, y mi amor por ti es tan infinito como el universo.",
  "Como el mar ama a la luna, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el mar.",
  "Eres mi arco iris, [nombre], llenando mi vida de color después de la lluvia, y mi amor por ti es mi promesa de siempre.",
  "Eres mi luz, [nombre], iluminando mi camino, y mi amor por ti es mi faro, siempre brillante.",
  "Como una flor en plena primavera, así florece mi amor por ti, [nombre], con cada pétalo, cada color, crece mi pasión.",
  "Eres mi melodía, [nombre], la canción que siempre quiero cantar, y cada nota es un eco de mi amor por ti.",
  "Eres mi refugio, [nombre], mi lugar seguro en medio de la tormenta, y mi amor por ti es mi ancla, siempre firme.",
  "Eres mi arco iris, [nombre], después de la tormenta, llenas mi vida de color y mi amor por ti es eterno.",
  "Como el océano ama a la luna, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el mar.",
  "[nombre], eres mi faro en la oscuridad, la luz que guía mi camino, y mi amor por ti es inquebrantable.",
  "Eres mi melodía, [nombre], la canción que siempre quiero cantar, cada nota es un eco de mi amor por ti.",
  "Eres mi sueño, [nombre], y cada día a tu lado es un regalo, mi amor por ti es inmenso y siempre creciente.",
  "Como un río que fluye hacia el mar, así fluye mi amor hacia ti, [nombre], constante e inmutable.",
  "Eres mi refugio, [nombre], mi lugar seguro en medio de la tormenta, y mi amor por ti es mi ancla.",
  "Eres mi luna, [nombre], iluminando mis noches más oscuras, y mi amor por ti es como las estrellas, infinito y siempre brillante.",
  "Como el viento que acaricia las hojas, así es mi amor por ti, [nombre], suave pero constante, siempre presente.",
  "Eres mi sol, [nombre], iluminando mi mundo, y mi amor por ti es como el cielo, sin fin y siempre azul.",
  "Eres mi todo, [nombre], mi sol, mi luna, mis estrellas, y mi amor por ti es tan infinito como el universo.",
  "Como el mar ama a la luna, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el océano.",
  "Eres mi canción, [nombre], cada nota, cada melodía, es un eco de mi amor por ti.",
  "Eres mi sueño hecho realidad, [nombre], y mi amor por ti es la realidad que quiero vivir cada día.",
  "Eres mi luz, [nombre], guiándome a través de la oscuridad, y mi amor por ti es mi faro.",
  "Eres mi arco iris, [nombre], apareciendo después de la lluvia, llenando mi vida de color, y mi amor por ti es mi promesa de siempre.",
  "Como el sol ama a la tierra, así te amo yo, [nombre], mi amor por ti es tan brillante y eterno como el sol.",
  "Eres mi refugio, [nombre], en medio de la tormenta, mi paz en el caos, y mi amor por ti es mi ancla.",
  "En el libro de mi vida, [nombre], eres mi capítulo favorito, cada palabra, cada línea, es una muestra de mi amor por ti.",
  "Eres mi luna, [nombre], iluminando mis noches más oscuras, y mi amor por ti es como las estrellas, infinito y siempre brillante.",
  "Eres mi amanecer, [nombre], cada día contigo es un nuevo comienzo, y mi amor por ti ilumina mi camino.",
  "Como el viento acaricia suavemente las flores, así acaricia mi amor tu corazón, [nombre], suave pero constante.",
  "[nombre], eres el faro que ilumina mis noches más oscuras, y mi amor por ti es mi guía.",
  "Eres mi melodía, [nombre], la canción que resuena en mi corazón, cada nota es un eco de mi amor por ti.",
  "Eres mi sueño, [nombre], y cada día a tu lado es un sueño hecho realidad, mi amor por ti es inmenso y siempre creciente.",
  "Como un río que fluye hacia el mar, así fluye mi amor hacia ti, [nombre], constante e inmutable.",
  "Eres mi refugio, [nombre], mi lugar seguro en medio de la tormenta, y mi amor por ti es mi ancla.",
  "Eres mi luna, [nombre], iluminando mis noches más oscuras, y mi amor por ti es como las estrellas, infinito y siempre brillante.",
  "Como el viento que acaricia las hojas, así es mi amor por ti, [nombre], suave pero constante, siempre presente.",
  "Eres mi sol, [nombre], iluminando mi mundo, y mi amor por ti es como el cielo, sin fin y siempre azul.",
  "Eres mi todo, [nombre], mi sol, mi luna, mis estrellas, y mi amor por ti es tan infinito como el universo.",
  "Como el mar ama a la luna, así te amo yo, [nombre], mi amor por ti es tan profundo y vasto como el océano.",
  "Eres mi canción, [nombre], cada nota, cada melodía, es un eco de mi amor por ti.",
  "Eres mi sueño hecho realidad, [nombre], y mi amor por ti es la realidad que quiero vivir cada día.",
  "Eres mi luz, [nombre], guiándome a través de la oscuridad, y mi amor por ti es mi faro.",
  "Eres mi arco iris, [nombre], apareciendo después de la lluvia, llenando mi vida de color, y mi amor por ti es mi promesa de siempre.",
  "Como el sol ama a la tierra, así te amo yo, [nombre], mi amor por ti es tan brillante y eterno como el sol.",
  "Eres mi refugio, [nombre], en medio de la tormenta, mi paz en el caos, y mi amor por ti es mi ancla.",
  "En el libro de mi vida, [nombre], eres mi capítulo favorito, cada palabra, cada línea, es una muestra de mi amor por ti.",
  "Eres mi luna, [nombre], iluminando mis noches más oscuras, y mi amor por ti es como las estrellas, infinito y siempre brillante.",
  // Agrega más poemas según sea necesario
];
